require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/source_pages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SourcePage. As you add validations to SourcePage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SourcePage.create! valid_attributes
      get source_pages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      source_page = SourcePage.create! valid_attributes
      get source_page_url(source_page)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_source_page_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      source_page = SourcePage.create! valid_attributes
      get edit_source_page_url(source_page)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SourcePage" do
        expect {
          post source_pages_url, params: { source_page: valid_attributes }
        }.to change(SourcePage, :count).by(1)
      end

      it "redirects to the created source_page" do
        post source_pages_url, params: { source_page: valid_attributes }
        expect(response).to redirect_to(source_page_url(SourcePage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SourcePage" do
        expect {
          post source_pages_url, params: { source_page: invalid_attributes }
        }.to change(SourcePage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post source_pages_url, params: { source_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested source_page" do
        source_page = SourcePage.create! valid_attributes
        patch source_page_url(source_page), params: { source_page: new_attributes }
        source_page.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the source_page" do
        source_page = SourcePage.create! valid_attributes
        patch source_page_url(source_page), params: { source_page: new_attributes }
        source_page.reload
        expect(response).to redirect_to(source_page_url(source_page))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        source_page = SourcePage.create! valid_attributes
        patch source_page_url(source_page), params: { source_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested source_page" do
      source_page = SourcePage.create! valid_attributes
      expect {
        delete source_page_url(source_page)
      }.to change(SourcePage, :count).by(-1)
    end

    it "redirects to the source_pages list" do
      source_page = SourcePage.create! valid_attributes
      delete source_page_url(source_page)
      expect(response).to redirect_to(source_pages_url)
    end
  end
end
