default: &default
  adapter: postgresql
  encoding: utf8
  schema_search_path: public
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch('POSTGRES_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 20)%>


development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= "#{ENV['POSTGRES_DB']}_test" %>


production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
